
version: '3.8'

services:
  arangodb:
    image: arangodb:3.10
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=prowler
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8529"]
      interval: 5s
      timeout: 3s
      retries: 10

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # S3, and other services

  create-bucket:
    image: amazon/aws-cli
    depends_on:
      - localstack
    entrypoint: >
      sh -c "
        until aws --endpoint-url=http://localstack:4566 s3 ls > /dev/null 2>&1; do
          echo 'Waiting for LocalStack...';
          sleep 2;
        done;
        aws --endpoint-url=http://localstack:4566 s3 mb s3://prowler-poc-bucket;
        aws --endpoint-url=http://localstack:4566 s3api put-bucket-acl --bucket prowler-poc-bucket --acl public-read;
        aws --endpoint-url=http://localstack:4566 s3api put-bucket-tagging --bucket prowler-poc-bucket --tagging 'TagSet=[{Key=sensitivity,Value=high}]';
        until aws --endpoint-url=http://localstack:4566 s3 ls s3://prowler-poc-bucket > /dev/null 2>&1; do
          echo 'Waiting for prowler-poc-bucket to be created...';
          sleep 2;
        done;
      "
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1

  ingestor:
    build:
      context: ./ingestor
    volumes:
      - ./ingestor/iam_policy.json:/iam_policy.json
    depends_on:
      arangodb:
        condition: service_healthy
      create-bucket:
        condition: service_completed_successfully
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_IAM_POLICY_FILE=/iam_policy.json

  engine:
    build:
      context: ./engine
    depends_on:
      arangodb:
        condition: service_healthy
      remediation:
        condition: service_started
    environment:
      - REMEDIATION_SERVICE_URL=http://remediation:5001

  remediation:
    build:
      context: ./remediation
    ports:
      - "5001:5001"
    volumes:
      - ./remediations:/app/remediations
