version: '3.8'

services:
  arangodb:
    image: arangodb:3.10
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=prowler

  ingestor:
    build:
      context: ./ingestor
    depends_on:
      - arangodb

  engine:
    build:
      context: ./engine
    depends_on:
      - arangodb
